# Generated by Django 5.0.2 on 2024-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_comment_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
