# Generated by Django 5.0.2 on 2024-03-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_comment_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recommend',
        ),
    ]
